name: CD

on:
  push:
    branches: [main]
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  # ========================================
  # Build and Push Docker Images
  # ========================================
  docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract version
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          echo "VERSION_NO_PREFIX=${VERSION#v}" >> $GITHUB_OUTPUT

      - name: Build and push API image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.api
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/academic-assistant-api:${{ steps.version.outputs.VERSION_NO_PREFIX }}
            ${{ secrets.DOCKER_USERNAME }}/academic-assistant-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push Web image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.web
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/academic-assistant-web:${{ steps.version.outputs.VERSION_NO_PREFIX }}
            ${{ secrets.DOCKER_USERNAME }}/academic-assistant-web:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push MCP servers images
        uses: docker/build-push-action@v5
        with:
          context: ./packages/mcp-servers
          file: ./Dockerfile.mcp
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/literature-search-mcp:${{ steps.version.outputs.VERSION_NO_PREFIX }}
            ${{ secrets.DOCKER_USERNAME }}/literature-search-mcp:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  # ========================================
  # Deploy to Production
  # ========================================
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [docker]
    if: github.event_name == 'release'
    environment:
      name: production
      url: https://app.academic-assistant.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to Railway
        uses: railwayapp/cli-action@v1
        with:
          railway-token: ${{ secrets.RAILWAY_TOKEN }}
          command: up

      - name: Run database migrations
        run: |
          curl -X POST ${{ secrets.DEPLOY_WEBHOOK_URL }}/migrate

      - name: Health check
        run: |
          for i in {1..30}; do
            if curl -f https://api.academic-assistant.com/health; then
              echo "Deployment successful!"
              exit 0
            fi
            echo "Waiting for deployment... ($i/30)"
            sleep 10
          done
          echo "Deployment failed!"
          exit 1

      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          text: |
            Deployment to production completed!
            Version: ${{ github.ref_name }}
            Commit: ${{ github.sha }}
          webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()

  # ========================================
  # Create Release Notes
  # ========================================
  release-notes:
    name: Generate Release Notes
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Generate release notes
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { execSync } = require('child_process');

            // Get the previous release tag
            const tags = execSync('git tag -l --sort=-v:refname').toString().split('\n');
            const currentTag = '${{ github.ref_name }}';
            const currentIndex = tags.indexOf(currentTag);
            const previousTag = currentIndex < tags.length - 1 ? tags[currentIndex + 1] : null;

            // Get commits since previous release
            const range = previousTag ? `${previousTag}..${currentTag}` : currentTag;
            const commits = execSync(`git log ${range} --pretty=format:"- %s (%h)"`).toString();

            // Get contributors
            const contributors = execSync(`git shortlog -sn ${range}`).toString();

            const releaseNotes = `## What's Changed

            ### Commits
            ${commits}

            ### Contributors
            ${contributors}

            Full Changelog: https://github.com/${{ github.repository }}/compare/${previousTag || 'initial'}...${currentTag}
            `;

            console.log(releaseNotes);
            core.setOutput('notes', releaseNotes);

      - name: Update release with notes
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.rest.repos.updateRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: context.payload.release.id,
              body: '${{ steps.release-notes.outputs.notes }}'
            });

  # ========================================
  # Deploy to Staging (on push to main)
  # ========================================
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    environment:
      name: staging
      url: https://staging.academic-assistant.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build application
        run: pnpm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./apps/web
